package com.zzw.github.graphql.schema.interfaces;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@ImplementedBy({
        "com.zzw.github.graphql.schema.objects.AddedToProjectEvent",
        "com.zzw.github.graphql.schema.objects.App",
        "com.zzw.github.graphql.schema.objects.AssignedEvent",
        "com.zzw.github.graphql.schema.objects.BaseRefChangedEvent",
        "com.zzw.github.graphql.schema.objects.BaseRefForcePushedEvent",
        "com.zzw.github.graphql.schema.objects.Blob",
        "com.zzw.github.graphql.schema.objects.Bot",
        "com.zzw.github.graphql.schema.objects.BranchProtectionRule",
        "com.zzw.github.graphql.schema.objects.CheckRun",
        "com.zzw.github.graphql.schema.objects.CheckSuite",
        "com.zzw.github.graphql.schema.objects.ClosedEvent",
        "com.zzw.github.graphql.schema.objects.CommentDeletedEvent",
        "com.zzw.github.graphql.schema.objects.Commit",
        "com.zzw.github.graphql.schema.objects.CommitComment",
        "com.zzw.github.graphql.schema.objects.CommitCommentThread",
        "com.zzw.github.graphql.schema.objects.ConvertedNoteToIssueEvent",
        "com.zzw.github.graphql.schema.objects.CrossReferencedEvent",
        "com.zzw.github.graphql.schema.objects.DemilestonedEvent",
        "com.zzw.github.graphql.schema.objects.DependencyGraphManifest",
        "com.zzw.github.graphql.schema.objects.DeployKey",
        "com.zzw.github.graphql.schema.objects.DeployedEvent",
        "com.zzw.github.graphql.schema.objects.Deployment",
        "com.zzw.github.graphql.schema.objects.DeploymentEnvironmentChangedEvent",
        "com.zzw.github.graphql.schema.objects.DeploymentStatus",
        "com.zzw.github.graphql.schema.objects.ExternalIdentity",
        "com.zzw.github.graphql.schema.objects.Gist",
        "com.zzw.github.graphql.schema.objects.GistComment",
        "com.zzw.github.graphql.schema.objects.HeadRefDeletedEvent",
        "com.zzw.github.graphql.schema.objects.HeadRefForcePushedEvent",
        "com.zzw.github.graphql.schema.objects.HeadRefRestoredEvent",
        "com.zzw.github.graphql.schema.objects.Issue",
        "com.zzw.github.graphql.schema.objects.IssueComment",
        "com.zzw.github.graphql.schema.objects.Label",
        "com.zzw.github.graphql.schema.objects.LabeledEvent",
        "com.zzw.github.graphql.schema.objects.Language",
        "com.zzw.github.graphql.schema.objects.License",
        "com.zzw.github.graphql.schema.objects.LockedEvent",
        "com.zzw.github.graphql.schema.objects.MarketplaceCategory",
        "com.zzw.github.graphql.schema.objects.MarketplaceListing",
        "com.zzw.github.graphql.schema.objects.MentionedEvent",
        "com.zzw.github.graphql.schema.objects.MergedEvent",
        "com.zzw.github.graphql.schema.objects.Milestone",
        "com.zzw.github.graphql.schema.objects.MilestonedEvent",
        "com.zzw.github.graphql.schema.objects.MovedColumnsInProjectEvent",
        "com.zzw.github.graphql.schema.objects.Organization",
        "com.zzw.github.graphql.schema.objects.OrganizationIdentityProvider",
        "com.zzw.github.graphql.schema.objects.OrganizationInvitation",
        "com.zzw.github.graphql.schema.objects.Project",
        "com.zzw.github.graphql.schema.objects.ProjectCard",
        "com.zzw.github.graphql.schema.objects.ProjectColumn",
        "com.zzw.github.graphql.schema.objects.ProtectedBranch",
        "com.zzw.github.graphql.schema.objects.PublicKey",
        "com.zzw.github.graphql.schema.objects.PullRequest",
        "com.zzw.github.graphql.schema.objects.PullRequestCommit",
        "com.zzw.github.graphql.schema.objects.PullRequestCommitCommentThread",
        "com.zzw.github.graphql.schema.objects.PullRequestReview",
        "com.zzw.github.graphql.schema.objects.PullRequestReviewComment",
        "com.zzw.github.graphql.schema.objects.PullRequestReviewThread",
        "com.zzw.github.graphql.schema.objects.Push",
        "com.zzw.github.graphql.schema.objects.PushAllowance",
        "com.zzw.github.graphql.schema.objects.Reaction",
        "com.zzw.github.graphql.schema.objects.Ref",
        "com.zzw.github.graphql.schema.objects.ReferencedEvent",
        "com.zzw.github.graphql.schema.objects.Release",
        "com.zzw.github.graphql.schema.objects.ReleaseAsset",
        "com.zzw.github.graphql.schema.objects.RemovedFromProjectEvent",
        "com.zzw.github.graphql.schema.objects.RenamedTitleEvent",
        "com.zzw.github.graphql.schema.objects.ReopenedEvent",
        "com.zzw.github.graphql.schema.objects.Repository",
        "com.zzw.github.graphql.schema.objects.RepositoryInvitation",
        "com.zzw.github.graphql.schema.objects.RepositoryTopic",
        "com.zzw.github.graphql.schema.objects.RepositoryVulnerabilityAlert",
        "com.zzw.github.graphql.schema.objects.ReviewDismissalAllowance",
        "com.zzw.github.graphql.schema.objects.ReviewDismissedEvent",
        "com.zzw.github.graphql.schema.objects.ReviewRequest",
        "com.zzw.github.graphql.schema.objects.ReviewRequestRemovedEvent",
        "com.zzw.github.graphql.schema.objects.ReviewRequestedEvent",
        "com.zzw.github.graphql.schema.objects.Status",
        "com.zzw.github.graphql.schema.objects.StatusContext",
        "com.zzw.github.graphql.schema.objects.SubscribedEvent",
        "com.zzw.github.graphql.schema.objects.Tag",
        "com.zzw.github.graphql.schema.objects.Team",
        "com.zzw.github.graphql.schema.objects.TeamDiscussion",
        "com.zzw.github.graphql.schema.objects.TeamDiscussionComment",
        "com.zzw.github.graphql.schema.objects.Topic",
        "com.zzw.github.graphql.schema.objects.Tree",
        "com.zzw.github.graphql.schema.objects.UnassignedEvent",
        "com.zzw.github.graphql.schema.objects.UnlabeledEvent",
        "com.zzw.github.graphql.schema.objects.UnlockedEvent",
        "com.zzw.github.graphql.schema.objects.UnsubscribedEvent",
        "com.zzw.github.graphql.schema.objects.User",
        "com.zzw.github.graphql.schema.objects.UserContentEdit",
})
@Description("An object with an ID.")
public interface Node {
    public com.zzw.github.graphql.schema.scalars.ID getId();
    public void setId(com.zzw.github.graphql.schema.scalars.ID id);
}
