package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of AddPullRequestReviewComment")
public class AddPullRequestReviewCommentInput {
    @NonNull("!")
    @Description("The text of the comment.")
    private com.zzw.github.graphql.schema.scalars.String body;
    public com.zzw.github.graphql.schema.scalars.String getBody() { return this.body; }
    public void setBody(com.zzw.github.graphql.schema.scalars.String body) { this.body = body; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }

    @Description("The SHA of the commit to comment on.")
    private com.zzw.github.graphql.schema.scalars.GitObjectID commitOID;
    public com.zzw.github.graphql.schema.scalars.GitObjectID getCommitOID() { return this.commitOID; }
    public void setCommitOID(com.zzw.github.graphql.schema.scalars.GitObjectID commitOID) { this.commitOID = commitOID; }

    @Description("The comment id to reply to.")
    private com.zzw.github.graphql.schema.scalars.ID inReplyTo;
    public com.zzw.github.graphql.schema.scalars.ID getInReplyTo() { return this.inReplyTo; }
    public void setInReplyTo(com.zzw.github.graphql.schema.scalars.ID inReplyTo) { this.inReplyTo = inReplyTo; }

    @Description("The relative path of the file to comment on.")
    private com.zzw.github.graphql.schema.scalars.String path;
    public com.zzw.github.graphql.schema.scalars.String getPath() { return this.path; }
    public void setPath(com.zzw.github.graphql.schema.scalars.String path) { this.path = path; }

    @Description("The line index in the diff to comment on.")
    private com.zzw.github.graphql.schema.scalars.Int position;
    public com.zzw.github.graphql.schema.scalars.Int getPosition() { return this.position; }
    public void setPosition(com.zzw.github.graphql.schema.scalars.Int position) { this.position = position; }

    @NonNull("!")
    @Description("The Node ID of the review to modify.")
    private com.zzw.github.graphql.schema.scalars.ID pullRequestReviewId;
    public com.zzw.github.graphql.schema.scalars.ID getPullRequestReviewId() { return this.pullRequestReviewId; }
    public void setPullRequestReviewId(com.zzw.github.graphql.schema.scalars.ID pullRequestReviewId) { this.pullRequestReviewId = pullRequestReviewId; }
}
