package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of CreateTeamDiscussionComment")
public class CreateTeamDiscussionCommentInput {
    @NonNull("!")
    @Description("The content of the comment.")
    private com.zzw.github.graphql.schema.scalars.String body;
    public com.zzw.github.graphql.schema.scalars.String getBody() { return this.body; }
    public void setBody(com.zzw.github.graphql.schema.scalars.String body) { this.body = body; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }

    @NonNull("!")
    @Description("The ID of the discussion to which the comment belongs.")
    private com.zzw.github.graphql.schema.scalars.ID discussionId;
    public com.zzw.github.graphql.schema.scalars.ID getDiscussionId() { return this.discussionId; }
    public void setDiscussionId(com.zzw.github.graphql.schema.scalars.ID discussionId) { this.discussionId = discussionId; }
}
