package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of DeleteProjectCard")
public class DeleteProjectCardInput {
    @NonNull("!")
    @Description("The id of the card to delete.")
    private com.zzw.github.graphql.schema.scalars.ID cardId;
    public com.zzw.github.graphql.schema.scalars.ID getCardId() { return this.cardId; }
    public void setCardId(com.zzw.github.graphql.schema.scalars.ID cardId) { this.cardId = cardId; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }
}
