package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of DeleteBranchProtectionRule")
public class DeleteBranchProtectionRuleInput {
    @NonNull("!")
    @Description("The global relay id of the branch protection rule to be deleted.")
    private com.zzw.github.graphql.schema.scalars.ID branchProtectionRuleId;
    public com.zzw.github.graphql.schema.scalars.ID getBranchProtectionRuleId() { return this.branchProtectionRuleId; }
    public void setBranchProtectionRuleId(com.zzw.github.graphql.schema.scalars.ID branchProtectionRuleId) { this.branchProtectionRuleId = branchProtectionRuleId; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }
}
