package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of DismissPullRequestReview")
public class DismissPullRequestReviewInput {
    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }

    @NonNull("!")
    @Description("The contents of the pull request review dismissal message.")
    private com.zzw.github.graphql.schema.scalars.String message;
    public com.zzw.github.graphql.schema.scalars.String getMessage() { return this.message; }
    public void setMessage(com.zzw.github.graphql.schema.scalars.String message) { this.message = message; }

    @NonNull("!")
    @Description("The Node ID of the pull request review to modify.")
    private com.zzw.github.graphql.schema.scalars.ID pullRequestReviewId;
    public com.zzw.github.graphql.schema.scalars.ID getPullRequestReviewId() { return this.pullRequestReviewId; }
    public void setPullRequestReviewId(com.zzw.github.graphql.schema.scalars.ID pullRequestReviewId) { this.pullRequestReviewId = pullRequestReviewId; }
}
