package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of MoveProjectColumn")
public class MoveProjectColumnInput {
    @Description("Place the new column after the column with this id. Pass null to place it at the front.")
    private com.zzw.github.graphql.schema.scalars.ID afterColumnId;
    public com.zzw.github.graphql.schema.scalars.ID getAfterColumnId() { return this.afterColumnId; }
    public void setAfterColumnId(com.zzw.github.graphql.schema.scalars.ID afterColumnId) { this.afterColumnId = afterColumnId; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }

    @NonNull("!")
    @Description("The id of the column to move.")
    private com.zzw.github.graphql.schema.scalars.ID columnId;
    public com.zzw.github.graphql.schema.scalars.ID getColumnId() { return this.columnId; }
    public void setColumnId(com.zzw.github.graphql.schema.scalars.ID columnId) { this.columnId = columnId; }
}
