package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of RemoveStar")
public class RemoveStarInput {
    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }

    @NonNull("!")
    @Description("The Starrable ID to unstar.")
    private com.zzw.github.graphql.schema.scalars.ID starrableId;
    public com.zzw.github.graphql.schema.scalars.ID getStarrableId() { return this.starrableId; }
    public void setStarrableId(com.zzw.github.graphql.schema.scalars.ID starrableId) { this.starrableId = starrableId; }
}
