package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of RemoveAssigneesFromAssignable")
public class RemoveAssigneesFromAssignableInput {
    @NonNull("!")
    @Description("The id of the assignable object to remove assignees from.")
    private com.zzw.github.graphql.schema.scalars.ID assignableId;
    public com.zzw.github.graphql.schema.scalars.ID getAssignableId() { return this.assignableId; }
    public void setAssignableId(com.zzw.github.graphql.schema.scalars.ID assignableId) { this.assignableId = assignableId; }

    @NonNull("[!]!")
    @Description("The id of users to remove as assignees.")
    private com.zzw.github.graphql.schema.scalars.ID[] assigneeIds;
    public com.zzw.github.graphql.schema.scalars.ID[] getAssigneeIds() { return this.assigneeIds; }
    public void setAssigneeIds(com.zzw.github.graphql.schema.scalars.ID[] assigneeIds) { this.assigneeIds = assigneeIds; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }
}
