package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of SubmitPullRequestReview")
public class SubmitPullRequestReviewInput {
    @Description("The text field to set on the Pull Request Review.")
    private com.zzw.github.graphql.schema.scalars.String body;
    public com.zzw.github.graphql.schema.scalars.String getBody() { return this.body; }
    public void setBody(com.zzw.github.graphql.schema.scalars.String body) { this.body = body; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }

    @NonNull("!")
    @Description("The event to send to the Pull Request Review.")
    private com.zzw.github.graphql.schema.enums.PullRequestReviewEvent event;
    public com.zzw.github.graphql.schema.enums.PullRequestReviewEvent getEvent() { return this.event; }
    public void setEvent(com.zzw.github.graphql.schema.enums.PullRequestReviewEvent event) { this.event = event; }

    @NonNull("!")
    @Description("The Pull Request Review ID to submit.")
    private com.zzw.github.graphql.schema.scalars.ID pullRequestReviewId;
    public com.zzw.github.graphql.schema.scalars.ID getPullRequestReviewId() { return this.pullRequestReviewId; }
    public void setPullRequestReviewId(com.zzw.github.graphql.schema.scalars.ID pullRequestReviewId) { this.pullRequestReviewId = pullRequestReviewId; }
}
