package com.zzw.github.graphql.schema.inputobjects;

import com.zzw.github.graphql.schema.annotations.Argument;
import com.zzw.github.graphql.schema.annotations.Arguments;
import com.zzw.github.graphql.schema.annotations.Description;
import com.zzw.github.graphql.schema.annotations.ImplementedBy;
import com.zzw.github.graphql.schema.annotations.NonNull;

@Description("Autogenerated input type of UpdateTeamDiscussion")
public class UpdateTeamDiscussionInput {
    @Description("The updated text of the discussion.")
    private com.zzw.github.graphql.schema.scalars.String body;
    public com.zzw.github.graphql.schema.scalars.String getBody() { return this.body; }
    public void setBody(com.zzw.github.graphql.schema.scalars.String body) { this.body = body; }

    @Description("The current version of the body content. If provided, this update operation will be rejected if the given version does not match the latest version on the server.")
    private com.zzw.github.graphql.schema.scalars.String bodyVersion;
    public com.zzw.github.graphql.schema.scalars.String getBodyVersion() { return this.bodyVersion; }
    public void setBodyVersion(com.zzw.github.graphql.schema.scalars.String bodyVersion) { this.bodyVersion = bodyVersion; }

    @Description("A unique identifier for the client performing the mutation.")
    private com.zzw.github.graphql.schema.scalars.String clientMutationId;
    public com.zzw.github.graphql.schema.scalars.String getClientMutationId() { return this.clientMutationId; }
    public void setClientMutationId(com.zzw.github.graphql.schema.scalars.String clientMutationId) { this.clientMutationId = clientMutationId; }

    @NonNull("!")
    @Description("The Node ID of the discussion to modify.")
    private com.zzw.github.graphql.schema.scalars.ID id;
    public com.zzw.github.graphql.schema.scalars.ID getId() { return this.id; }
    public void setId(com.zzw.github.graphql.schema.scalars.ID id) { this.id = id; }

    @Description("If provided, sets the pinned state of the updated discussion.")
    private com.zzw.github.graphql.schema.scalars.Boolean pinned;
    public com.zzw.github.graphql.schema.scalars.Boolean getPinned() { return this.pinned; }
    public void setPinned(com.zzw.github.graphql.schema.scalars.Boolean pinned) { this.pinned = pinned; }

    @Description("The updated title of the discussion.")
    private com.zzw.github.graphql.schema.scalars.String title;
    public com.zzw.github.graphql.schema.scalars.String getTitle() { return this.title; }
    public void setTitle(com.zzw.github.graphql.schema.scalars.String title) { this.title = title; }
}
